schema = 3

[mod]
  [mod.'github.com/emanspeaks/amdgpu-go']
    version = 'v0.2.5'
    hash = 'sha256-uFUcIk6Hyq9kM+r4s7DIhykXeqheiVU+oSXS5nPCU2I='

  [mod.'github.com/godbus/dbus/v5']
    version = 'v5.2.2'
    hash = 'sha256-j+LicPlXcB1R3oVFPa8cd4yVJLpBx+ca5gXmHqOJSN8='

  [mod.'github.com/gorilla/websocket']
    version = 'v1.5.3'
    hash = 'sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0='

  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='
